[package]
name = "immortal-ask-game"
description = "Game logic service for 宿命劫：问仙"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "game"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bevy_ecs.workspace = true
crossbeam.workspace = true
dotenvy.workspace = true
immortal-ask-common = { path = "../common" }
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
